name: Markdown Lint CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run markdown lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install markdown lint and dependencies
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json

      - name: Run markdown lint and output to JSON
        run: |
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json > remark-lint-report.json

      - name: Upload remark lint report
        uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: remark-lint-report.json


